--totalcustomers by countries
SElECT  
country ,
COUNT(customer_key) as total_customers
from [gold.dim_customers]
GROUP BY country
ORDER BY total_customers DESC

--total customers by gender
SElECT  
gender ,
COUNT(customer_key) as total_customers
from [gold.dim_customers]
GROUP BY gender
ORDER BY total_customers DESC

--total products by category
SELECT 
category ,
COUNT(product_key) as total_products
FROM [gold.dim_products]
GROUP BY category
ORDER BY total_products DESC

-- the Average costs in each category 
SELECT 
category ,
AVG(cost) as avg_costs
FROM [gold.dim_products]
GROUP BY category
ORDER BY avg_costs DESC

--the total Ravenue generated for each category
SELECT 
p.category,
SUM (f.sales_amount) total_revenue
FROM [gold.fact_sales] f
LEFT JOIN [gold.dim_products] p
ON p.product_key=f.product_key
GROUP BY p.category
ORDER BY total_revenue DESC

--the total revenue generated by Each Customer
SELECT 
c.customer_key,
c.first_name,
c.last_name,
SUM (f.sales_amount) AS total_revenue
FROM [gold.fact_sales] f
LEFT JOIN [gold.dim_customers] c
ON c.customer_key= f.customer_key
GROUP BY 
c.customer_key,
c.first_name,
c.last_name
ORDER BY total_revenue DESC

-- the Distribution of sold items across Countries
SELECT 
c.country,
SUM (f.quantity) AS total_sold_items
FROM [gold.fact_sales] f
LEFT JOIN [gold.dim_customers] c
ON c.customer_key= f.customer_key
GROUP BY 
c.country
ORDER BY total_sold_items DESC